// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: im.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendTextMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sync    int64  `protobuf:"varint,1,opt,name=sync,proto3" json:"sync,omitempty"` //	Integer	选填	1：把消息同步到 From_Account 在线终端和漫游上 2：消息不同步至 From_Account；若不填写默认情况下会将消息存 From_Account 漫游
	FromUid int64  `protobuf:"varint,2,opt,name=fromUid,proto3" json:"fromUid,omitempty"`
	ToUid   int64  `protobuf:"varint,3,opt,name=toUid,proto3" json:"toUid,omitempty"`
	Text    string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"` //
}

func (x *SendTextMsgReq) Reset() {
	*x = SendTextMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTextMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextMsgReq) ProtoMessage() {}

func (x *SendTextMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextMsgReq.ProtoReflect.Descriptor instead.
func (*SendTextMsgReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{0}
}

func (x *SendTextMsgReq) GetSync() int64 {
	if x != nil {
		return x.Sync
	}
	return 0
}

func (x *SendTextMsgReq) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *SendTextMsgReq) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *SendTextMsgReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendTextMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionStatus string `protobuf:"bytes,1,opt,name=ActionStatus,proto3" json:"ActionStatus,omitempty"`
	ErrorInfo    string `protobuf:"bytes,2,opt,name=ErrorInfo,proto3" json:"ErrorInfo,omitempty"`
	ErrorCode    int32  `protobuf:"varint,3,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	MsgTime      int64  `protobuf:"varint,4,opt,name=MsgTime,proto3" json:"MsgTime,omitempty"`
	MsgKey       string `protobuf:"bytes,5,opt,name=MsgKey,proto3" json:"MsgKey,omitempty"`
}

func (x *SendTextMsgResp) Reset() {
	*x = SendTextMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTextMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextMsgResp) ProtoMessage() {}

func (x *SendTextMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextMsgResp.ProtoReflect.Descriptor instead.
func (*SendTextMsgResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{1}
}

func (x *SendTextMsgResp) GetActionStatus() string {
	if x != nil {
		return x.ActionStatus
	}
	return ""
}

func (x *SendTextMsgResp) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

func (x *SendTextMsgResp) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *SendTextMsgResp) GetMsgTime() int64 {
	if x != nil {
		return x.MsgTime
	}
	return 0
}

func (x *SendTextMsgResp) GetMsgKey() string {
	if x != nil {
		return x.MsgKey
	}
	return ""
}

type SendDefineMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUid int64  `protobuf:"varint,1,opt,name=fromUid,proto3" json:"fromUid,omitempty"`
	ToUid   int64  `protobuf:"varint,2,opt,name=toUid,proto3" json:"toUid,omitempty"`
	MsgType int64  `protobuf:"varint,3,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Title   string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Text    string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Val1    string `protobuf:"bytes,6,opt,name=val1,proto3" json:"val1,omitempty"`
	Val2    string `protobuf:"bytes,7,opt,name=val2,proto3" json:"val2,omitempty"`
	Val3    string `protobuf:"bytes,8,opt,name=val3,proto3" json:"val3,omitempty"`
	Val4    string `protobuf:"bytes,9,opt,name=val4,proto3" json:"val4,omitempty"`
	Val5    string `protobuf:"bytes,10,opt,name=val5,proto3" json:"val5,omitempty"`
	Val6    string `protobuf:"bytes,11,opt,name=val6,proto3" json:"val6,omitempty"`
	Sync    int64  `protobuf:"varint,12,opt,name=sync,proto3" json:"sync,omitempty"`
}

func (x *SendDefineMsgReq) Reset() {
	*x = SendDefineMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDefineMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDefineMsgReq) ProtoMessage() {}

func (x *SendDefineMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDefineMsgReq.ProtoReflect.Descriptor instead.
func (*SendDefineMsgReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{2}
}

func (x *SendDefineMsgReq) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *SendDefineMsgReq) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *SendDefineMsgReq) GetMsgType() int64 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *SendDefineMsgReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendDefineMsgReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendDefineMsgReq) GetVal1() string {
	if x != nil {
		return x.Val1
	}
	return ""
}

func (x *SendDefineMsgReq) GetVal2() string {
	if x != nil {
		return x.Val2
	}
	return ""
}

func (x *SendDefineMsgReq) GetVal3() string {
	if x != nil {
		return x.Val3
	}
	return ""
}

func (x *SendDefineMsgReq) GetVal4() string {
	if x != nil {
		return x.Val4
	}
	return ""
}

func (x *SendDefineMsgReq) GetVal5() string {
	if x != nil {
		return x.Val5
	}
	return ""
}

func (x *SendDefineMsgReq) GetVal6() string {
	if x != nil {
		return x.Val6
	}
	return ""
}

func (x *SendDefineMsgReq) GetSync() int64 {
	if x != nil {
		return x.Sync
	}
	return 0
}

type SendDefineMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int64  `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *SendDefineMsgResp) Reset() {
	*x = SendDefineMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDefineMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDefineMsgResp) ProtoMessage() {}

func (x *SendDefineMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDefineMsgResp.ProtoReflect.Descriptor instead.
func (*SendDefineMsgResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{3}
}

func (x *SendDefineMsgResp) GetErrCode() int64 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *SendDefineMsgResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

// 发送小程序订阅消息
type SendMiniProgramSubscribeMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thing4     string `protobuf:"bytes,1,opt,name=thing4,proto3" json:"thing4,omitempty"`
	Thing5     string `protobuf:"bytes,2,opt,name=thing5,proto3" json:"thing5,omitempty"`
	Time3      string `protobuf:"bytes,3,opt,name=time3,proto3" json:"time3,omitempty"`
	Time2      string `protobuf:"bytes,4,opt,name=time2,proto3" json:"time2,omitempty"`
	Thing1     string `protobuf:"bytes,5,opt,name=thing1,proto3" json:"thing1,omitempty"`
	Thing3     string `protobuf:"bytes,6,opt,name=thing3,proto3" json:"thing3,omitempty"`
	Date4      string `protobuf:"bytes,7,opt,name=date4,proto3" json:"date4,omitempty"`
	TemplateId string `protobuf:"bytes,8,opt,name=templateId,proto3" json:"templateId,omitempty"`
	OpenId     string `protobuf:"bytes,9,opt,name=openId,proto3" json:"openId,omitempty"` // 小程序openid
	Page       string `protobuf:"bytes,10,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *SendMiniProgramSubscribeMsgReq) Reset() {
	*x = SendMiniProgramSubscribeMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMiniProgramSubscribeMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMiniProgramSubscribeMsgReq) ProtoMessage() {}

func (x *SendMiniProgramSubscribeMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMiniProgramSubscribeMsgReq.ProtoReflect.Descriptor instead.
func (*SendMiniProgramSubscribeMsgReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{4}
}

func (x *SendMiniProgramSubscribeMsgReq) GetThing4() string {
	if x != nil {
		return x.Thing4
	}
	return ""
}

func (x *SendMiniProgramSubscribeMsgReq) GetThing5() string {
	if x != nil {
		return x.Thing5
	}
	return ""
}

func (x *SendMiniProgramSubscribeMsgReq) GetTime3() string {
	if x != nil {
		return x.Time3
	}
	return ""
}

func (x *SendMiniProgramSubscribeMsgReq) GetTime2() string {
	if x != nil {
		return x.Time2
	}
	return ""
}

func (x *SendMiniProgramSubscribeMsgReq) GetThing1() string {
	if x != nil {
		return x.Thing1
	}
	return ""
}

func (x *SendMiniProgramSubscribeMsgReq) GetThing3() string {
	if x != nil {
		return x.Thing3
	}
	return ""
}

func (x *SendMiniProgramSubscribeMsgReq) GetDate4() string {
	if x != nil {
		return x.Date4
	}
	return ""
}

func (x *SendMiniProgramSubscribeMsgReq) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendMiniProgramSubscribeMsgReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *SendMiniProgramSubscribeMsgReq) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

type SendMiniProgramSubscribeMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendMiniProgramSubscribeMsgResp) Reset() {
	*x = SendMiniProgramSubscribeMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMiniProgramSubscribeMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMiniProgramSubscribeMsgResp) ProtoMessage() {}

func (x *SendMiniProgramSubscribeMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMiniProgramSubscribeMsgResp.ProtoReflect.Descriptor instead.
func (*SendMiniProgramSubscribeMsgResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{5}
}

// 发送微信服务号模版消息
type SendFwhTemplateMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId string `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"` // 服务号消息模版id
	First      string `protobuf:"bytes,2,opt,name=first,proto3" json:"first,omitempty"`           // 标题
	Keyword1   string `protobuf:"bytes,3,opt,name=keyword1,proto3" json:"keyword1,omitempty"`
	Keyword2   string `protobuf:"bytes,4,opt,name=keyword2,proto3" json:"keyword2,omitempty"`
	Keyword3   string `protobuf:"bytes,5,opt,name=keyword3,proto3" json:"keyword3,omitempty"`
	Keyword4   string `protobuf:"bytes,6,opt,name=keyword4,proto3" json:"keyword4,omitempty"`
	Remark     string `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"` // 提示
	OpenId     string `protobuf:"bytes,8,opt,name=openId,proto3" json:"openId,omitempty"` // 服务号openid
	Path       string `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`     // 跳转小程序的路径
	Color      string `protobuf:"bytes,10,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *SendFwhTemplateMsgReq) Reset() {
	*x = SendFwhTemplateMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFwhTemplateMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFwhTemplateMsgReq) ProtoMessage() {}

func (x *SendFwhTemplateMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFwhTemplateMsgReq.ProtoReflect.Descriptor instead.
func (*SendFwhTemplateMsgReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{6}
}

func (x *SendFwhTemplateMsgReq) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendFwhTemplateMsgReq) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *SendFwhTemplateMsgReq) GetKeyword1() string {
	if x != nil {
		return x.Keyword1
	}
	return ""
}

func (x *SendFwhTemplateMsgReq) GetKeyword2() string {
	if x != nil {
		return x.Keyword2
	}
	return ""
}

func (x *SendFwhTemplateMsgReq) GetKeyword3() string {
	if x != nil {
		return x.Keyword3
	}
	return ""
}

func (x *SendFwhTemplateMsgReq) GetKeyword4() string {
	if x != nil {
		return x.Keyword4
	}
	return ""
}

func (x *SendFwhTemplateMsgReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *SendFwhTemplateMsgReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *SendFwhTemplateMsgReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SendFwhTemplateMsgReq) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type SendFwhTemplateMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendFwhTemplateMsgResp) Reset() {
	*x = SendFwhTemplateMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFwhTemplateMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFwhTemplateMsgResp) ProtoMessage() {}

func (x *SendFwhTemplateMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFwhTemplateMsgResp.ProtoReflect.Descriptor instead.
func (*SendFwhTemplateMsgResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{7}
}

// 根据用户的服务号openid获取用户的unionId
type GetUserUnionIdByFwhOpenIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
}

func (x *GetUserUnionIdByFwhOpenIdReq) Reset() {
	*x = GetUserUnionIdByFwhOpenIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserUnionIdByFwhOpenIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserUnionIdByFwhOpenIdReq) ProtoMessage() {}

func (x *GetUserUnionIdByFwhOpenIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserUnionIdByFwhOpenIdReq.ProtoReflect.Descriptor instead.
func (*GetUserUnionIdByFwhOpenIdReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserUnionIdByFwhOpenIdReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type GetUserUnionIdByFwhOpenIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnionId string `protobuf:"bytes,1,opt,name=unionId,proto3" json:"unionId,omitempty"`
}

func (x *GetUserUnionIdByFwhOpenIdResp) Reset() {
	*x = GetUserUnionIdByFwhOpenIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserUnionIdByFwhOpenIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserUnionIdByFwhOpenIdResp) ProtoMessage() {}

func (x *GetUserUnionIdByFwhOpenIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserUnionIdByFwhOpenIdResp.ProtoReflect.Descriptor instead.
func (*GetUserUnionIdByFwhOpenIdResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserUnionIdByFwhOpenIdResp) GetUnionId() string {
	if x != nil {
		return x.UnionId
	}
	return ""
}

// 生成小程序url link/schema
type GenWxMpUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path               string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Query              string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	ExpireIntervalDays int64  `protobuf:"varint,3,opt,name=expireIntervalDays,proto3" json:"expireIntervalDays,omitempty"`
	Type               int64  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"` // 1 安卓 2 ios
}

func (x *GenWxMpUrlReq) Reset() {
	*x = GenWxMpUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenWxMpUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenWxMpUrlReq) ProtoMessage() {}

func (x *GenWxMpUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenWxMpUrlReq.ProtoReflect.Descriptor instead.
func (*GenWxMpUrlReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{10}
}

func (x *GenWxMpUrlReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GenWxMpUrlReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GenWxMpUrlReq) GetExpireIntervalDays() int64 {
	if x != nil {
		return x.ExpireIntervalDays
	}
	return 0
}

func (x *GenWxMpUrlReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GenWxMpUrlResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GenWxMpUrlResp) Reset() {
	*x = GenWxMpUrlResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenWxMpUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenWxMpUrlResp) ProtoMessage() {}

func (x *GenWxMpUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenWxMpUrlResp.ProtoReflect.Descriptor instead.
func (*GenWxMpUrlResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{11}
}

func (x *GenWxMpUrlResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// im msg log
type AddImMsgLogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUid      int64  `protobuf:"varint,1,opt,name=fromUid,proto3" json:"fromUid,omitempty"`
	ToUid        int64  `protobuf:"varint,2,opt,name=toUid,proto3" json:"toUid,omitempty"`
	MsgTime      int64  `protobuf:"varint,3,opt,name=msgTime,proto3" json:"msgTime,omitempty"`
	MsgId        string `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
	MsgType      string `protobuf:"bytes,5,opt,name=msgType,proto3" json:"msgType,omitempty"`
	MsgSeq       int64  `protobuf:"varint,7,opt,name=msgSeq,proto3" json:"msgSeq,omitempty"`
	FromUserType int64  `protobuf:"varint,8,opt,name=fromUserType,proto3" json:"fromUserType,omitempty"`
}

func (x *AddImMsgLogReq) Reset() {
	*x = AddImMsgLogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddImMsgLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImMsgLogReq) ProtoMessage() {}

func (x *AddImMsgLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImMsgLogReq.ProtoReflect.Descriptor instead.
func (*AddImMsgLogReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{12}
}

func (x *AddImMsgLogReq) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *AddImMsgLogReq) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *AddImMsgLogReq) GetMsgTime() int64 {
	if x != nil {
		return x.MsgTime
	}
	return 0
}

func (x *AddImMsgLogReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *AddImMsgLogReq) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *AddImMsgLogReq) GetMsgSeq() int64 {
	if x != nil {
		return x.MsgSeq
	}
	return 0
}

func (x *AddImMsgLogReq) GetFromUserType() int64 {
	if x != nil {
		return x.FromUserType
	}
	return 0
}

type AddImMsgLogResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddImMsgLogResp) Reset() {
	*x = AddImMsgLogResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddImMsgLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImMsgLogResp) ProtoMessage() {}

func (x *AddImMsgLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImMsgLogResp.ProtoReflect.Descriptor instead.
func (*AddImMsgLogResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{13}
}

var File_im_proto protoreflect.FileDescriptor

var file_im_proto_rawDesc = []byte{
	0x0a, 0x08, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x68,
	0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x73, 0x79, 0x6e, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xa3, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d,
	0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x22, 0x92,
	0x02, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x55, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x76,
	0x61, 0x6c, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x32, 0x12,
	0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x33, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76,
	0x61, 0x6c, 0x33, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x34, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x35, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x76,
	0x61, 0x6c, 0x36, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x36, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73,
	0x79, 0x6e, 0x63, 0x22, 0x45, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x8e, 0x02, 0x0a, 0x1e, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x68, 0x69, 0x6e, 0x67, 0x34, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x35, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x35, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x6d, 0x65, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x6d, 0x65, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x69,
	0x6e, 0x67, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67,
	0x31, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x33, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74,
	0x65, 0x34, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x65, 0x34, 0x12,
	0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x21, 0x0a, 0x1f, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x97,
	0x02, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x77, 0x68, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x33, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x33, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x34, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x34, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64,
	0x46, 0x77, 0x68, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x36, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x55, 0x6e, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x42, 0x79, 0x46, 0x77, 0x68, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x1d, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x79, 0x46, 0x77,
	0x68, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x7d, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x57, 0x78, 0x4d, 0x70,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x2e, 0x0a, 0x12, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x44, 0x61, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x44, 0x61, 0x79, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x6e, 0x57, 0x78, 0x4d, 0x70, 0x55,
	0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0xc6, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64,
	0x49, 0x6d, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x66,
	0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72,
	0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x73,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x53, 0x65, 0x71, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x73, 0x67, 0x53, 0x65, 0x71, 0x12, 0x22, 0x0a,
	0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x32, 0xfe, 0x03, 0x0a, 0x02, 0x69, 0x6d, 0x12, 0x36, 0x0a, 0x0b, 0x73,
	0x65, 0x6e, 0x64, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x65, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x66, 0x0a, 0x1b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x73, 0x67,
	0x12, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x69,
	0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x12, 0x73, 0x65, 0x6e,
	0x64, 0x46, 0x77, 0x68, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12,
	0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x77, 0x68, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x46, 0x77, 0x68, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x60, 0x0a, 0x19, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x79, 0x46, 0x77, 0x68, 0x4f, 0x70, 0x65,
	0x6e, 0x49, 0x64, 0x12, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x79, 0x46, 0x77, 0x68, 0x4f, 0x70, 0x65, 0x6e,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x79, 0x46, 0x77, 0x68, 0x4f, 0x70,
	0x65, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x57,
	0x78, 0x4d, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6e, 0x57,
	0x78, 0x4d, 0x70, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x6e, 0x57, 0x78, 0x4d, 0x70, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x12, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_im_proto_rawDescOnce sync.Once
	file_im_proto_rawDescData = file_im_proto_rawDesc
)

func file_im_proto_rawDescGZIP() []byte {
	file_im_proto_rawDescOnce.Do(func() {
		file_im_proto_rawDescData = protoimpl.X.CompressGZIP(file_im_proto_rawDescData)
	})
	return file_im_proto_rawDescData
}

var file_im_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_im_proto_goTypes = []interface{}{
	(*SendTextMsgReq)(nil),                  // 0: pb.SendTextMsgReq
	(*SendTextMsgResp)(nil),                 // 1: pb.SendTextMsgResp
	(*SendDefineMsgReq)(nil),                // 2: pb.SendDefineMsgReq
	(*SendDefineMsgResp)(nil),               // 3: pb.SendDefineMsgResp
	(*SendMiniProgramSubscribeMsgReq)(nil),  // 4: pb.SendMiniProgramSubscribeMsgReq
	(*SendMiniProgramSubscribeMsgResp)(nil), // 5: pb.SendMiniProgramSubscribeMsgResp
	(*SendFwhTemplateMsgReq)(nil),           // 6: pb.SendFwhTemplateMsgReq
	(*SendFwhTemplateMsgResp)(nil),          // 7: pb.SendFwhTemplateMsgResp
	(*GetUserUnionIdByFwhOpenIdReq)(nil),    // 8: pb.GetUserUnionIdByFwhOpenIdReq
	(*GetUserUnionIdByFwhOpenIdResp)(nil),   // 9: pb.GetUserUnionIdByFwhOpenIdResp
	(*GenWxMpUrlReq)(nil),                   // 10: pb.GenWxMpUrlReq
	(*GenWxMpUrlResp)(nil),                  // 11: pb.GenWxMpUrlResp
	(*AddImMsgLogReq)(nil),                  // 12: pb.AddImMsgLogReq
	(*AddImMsgLogResp)(nil),                 // 13: pb.AddImMsgLogResp
}
var file_im_proto_depIdxs = []int32{
	0,  // 0: pb.im.sendTextMsg:input_type -> pb.SendTextMsgReq
	2,  // 1: pb.im.sendDefineMsg:input_type -> pb.SendDefineMsgReq
	4,  // 2: pb.im.sendMiniProgramSubscribeMsg:input_type -> pb.SendMiniProgramSubscribeMsgReq
	6,  // 3: pb.im.sendFwhTemplateMsg:input_type -> pb.SendFwhTemplateMsgReq
	8,  // 4: pb.im.getUserUnionIdByFwhOpenId:input_type -> pb.GetUserUnionIdByFwhOpenIdReq
	10, // 5: pb.im.GenWxMpUrl:input_type -> pb.GenWxMpUrlReq
	12, // 6: pb.im.AddImMsgLog:input_type -> pb.AddImMsgLogReq
	1,  // 7: pb.im.sendTextMsg:output_type -> pb.SendTextMsgResp
	3,  // 8: pb.im.sendDefineMsg:output_type -> pb.SendDefineMsgResp
	5,  // 9: pb.im.sendMiniProgramSubscribeMsg:output_type -> pb.SendMiniProgramSubscribeMsgResp
	7,  // 10: pb.im.sendFwhTemplateMsg:output_type -> pb.SendFwhTemplateMsgResp
	9,  // 11: pb.im.getUserUnionIdByFwhOpenId:output_type -> pb.GetUserUnionIdByFwhOpenIdResp
	11, // 12: pb.im.GenWxMpUrl:output_type -> pb.GenWxMpUrlResp
	13, // 13: pb.im.AddImMsgLog:output_type -> pb.AddImMsgLogResp
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_im_proto_init() }
func file_im_proto_init() {
	if File_im_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_im_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTextMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTextMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDefineMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDefineMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMiniProgramSubscribeMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMiniProgramSubscribeMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFwhTemplateMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFwhTemplateMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserUnionIdByFwhOpenIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserUnionIdByFwhOpenIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenWxMpUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenWxMpUrlResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddImMsgLogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddImMsgLogResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_im_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_proto_goTypes,
		DependencyIndexes: file_im_proto_depIdxs,
		MessageInfos:      file_im_proto_msgTypes,
	}.Build()
	File_im_proto = out.File
	file_im_proto_rawDesc = nil
	file_im_proto_goTypes = nil
	file_im_proto_depIdxs = nil
}
