// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	mp "jakarta/app/im/api/internal/handler/mp"
	tim "jakarta/app/im/api/internal/handler/tim"
	"jakarta/app/im/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/tim/callback",
				Handler: tim.CallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/im/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/wx/mp/url/baidu",
				Handler: mp.GenBaiduMpUrlHandler(serverCtx),
			},
		},
		rest.WithPrefix("/im/v1"),
	)
}
