// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	payment "jakarta/app/payment/api/internal/handler/payment"
	third "jakarta/app/payment/api/internal/handler/third"
	"jakarta/app/payment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/third/wxpaycallback",
				Handler: third.WxPayCallbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/third/wxrefundcallback",
				Handler: third.WxRefundCallbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/third/hfbfcallback",
				Handler: third.HfbfCashCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/payment/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/payment/wxpay",
				Handler: payment.PaymentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/payment/v1"),
	)
}
