// Code generated by goctl. DO NOT EDIT!

package listenerPgModel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	listenerUserRecommendStatFieldNames          = builder.RawFieldNames(&ListenerUserRecommendStat{}, true)
	listenerUserRecommendStatRows                = strings.Join(listenerUserRecommendStatFieldNames, ",")
	listenerUserRecommendStatRowsExpectAutoSet   = strings.Join(stringx.Remove(listenerUserRecommendStatFieldNames, "create_time", "update_time", "create_t", "update_at"), ",")
	listenerUserRecommendStatRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(listenerUserRecommendStatFieldNames, "id", "create_time", "update_time", "create_at", "update_at"))
)

type (
	listenerUserRecommendStatModel interface {
		Insert(ctx context.Context, data *ListenerUserRecommendStat) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ListenerUserRecommendStat, error)
		Update(ctx context.Context, data *ListenerUserRecommendStat) error
		Delete(ctx context.Context, id string) error
	}

	defaultListenerUserRecommendStatModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ListenerUserRecommendStat struct {
		CreateTime    time.Time    `db:"create_time"`
		UpdateTime    time.Time    `db:"update_time"`
		Id            string       `db:"id"`
		Uid           int64        `db:"uid"`
		ListenerUid   int64        `db:"listener_uid"`
		RecommendTime sql.NullTime `db:"recommend_time"`
		RecommendCnt  int64        `db:"recommend_cnt"`
	}
)

func newListenerUserRecommendStatModel(conn sqlx.SqlConn) *defaultListenerUserRecommendStatModel {
	return &defaultListenerUserRecommendStatModel{
		conn:  conn,
		table: `"jakarta"."listener_user_recommend_stat"`,
	}
}

func (m *defaultListenerUserRecommendStatModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultListenerUserRecommendStatModel) FindOne(ctx context.Context, id string) (*ListenerUserRecommendStat, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", listenerUserRecommendStatRows, m.table)
	var resp ListenerUserRecommendStat
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultListenerUserRecommendStatModel) Insert(ctx context.Context, data *ListenerUserRecommendStat) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, listenerUserRecommendStatRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Uid, data.ListenerUid, data.RecommendTime, data.RecommendCnt)
	return ret, err
}

func (m *defaultListenerUserRecommendStatModel) Update(ctx context.Context, data *ListenerUserRecommendStat) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, listenerUserRecommendStatRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Uid, data.ListenerUid, data.RecommendTime, data.RecommendCnt)
	return err
}

func (m *defaultListenerUserRecommendStatModel) tableName() string {
	return m.table
}
